### PR TITLE
Convert `loadProps.gradle` to Kotlin script

### PR DESCRIPTION
**Pull request by sschuberth**
Ready for review

This is for consistency with all the other Gradle files.

### CODE REVIEW

**Review by sgammon — APPROVED** [review]

**Comment by sgammon** [comment]
@sschuberth hey, thank you so much for this!

**Comment by sschuberth** [comment]
@sgammon can you tell whether the failures are due to my change, or is something else going on?

**Comment by sgammon** [comment]
@sschuberth i pulled down and tested locally, it looks like CI on `v3` is just out of date. `release/alpha2` and `feature/js-runtime-v3` are where development is happening right now.

cherry-picking to `release/alpha2` worked fine, i may re-target the PR to that branch and merge there instead.

all the tests passed of course, it looks like your change is fine.

**Comment by sgammon** [comment]
@sschuberth now it's complaining because build secrets aren't making it in -- this is the first contribution btw outside of the core team! so i may need to tweak the workflows to allow the secrets, because they aren't really all that sensitive. it's just code coverage reporting, etc.

the tests all pass locally, so i think we can safely ignore CI and merge. thank you so much for your contribution, even though it's small, it means an enormous amount to us, since it's the first one! 🎉

**Comment by sgammon** [comment]
new check run on `feat/js-runtime-v3` [looking fine](https://github.com/elide-dev/v3/actions/runs/3825089469/jobs/6507791398).

**Comment by sschuberth** [comment]
> even though it's small, it means an enormous amount to us, since it's the first one! 🎉

It was just a test balloon from my side 😉 This project sounds really cool, and if it turns out to be of use in one of my projects, I hope to be able to make more contributions!

**Comment by sgammon** [comment]
hey, test balloon or not, we'll take it @sschuberth! lol.

i see you're a Kotlin fan. feel free to join us on Kotlin Slack in `#framework-elide` if you have any suggestions or ideas you'd like to share. 💯

**Pull request merged**
